### ISSUE TITLE
{"parallel:false"} JSON problem

### ISSUE THREAD

**Issue by Maegner** [mercedesbenzio/SINFO-backend-challenge#7]
When I make an API call to my API to get a Dealer it returns something like:
{"id":"d4f4d287-1ad6-4968-a8ff-e9e0009ad5d1",
"name":"MB Porto",
"coordinate":{
                   "latitude":41.15629,
                   "longitude":-8.645977
},"vehicles":{"parallel":false},           <--------- Not supose to happen
"closed":["thursday","wednesday"]
}
Is that a problem?
If it is can anyone help me fix it? I tried to search the web but I found nothing.
I am using Java, Mvn and SpringBoot Framework to build the API.

**Comment by lmmendes** [comment]
Hi @Maegner ,

Unfortunately, I can't help you, it seems to be an implementation issue, try revising the implementation of the serializer.

**Comment by Maegner** [comment]
I was unintendedly trying to send a Stream of Vehicles so, Jackson Serializer couldn't serialize it, so i changed the getter and now it's working.
 Thank you.

**Comment by FranzSkuffka** [comment]
@Maegner - Use triple backticks to format blocks of code in markdown please :)
https://help.github.com/articles/creating-and-highlighting-code-blocks/
